---
- name: Configure Multipass Node
  hosts: multipass_node
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install dependencies for Terraform and K3s
      apt:
        name:
          - wget
          - unzip
          - gnupg
          - lsb-release
          - curl
        state: present

    - name: Add HashiCorp GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor > /usr/share/keyrings/hashicorp-archive-keyring.gpg 2>/dev/null
      args:
        executable: /bin/bash

    - name: Add HashiCorp APT repository
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/hashicorp.list
        content: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"

    - name: Install Terraform
      ansible.builtin.apt:
        name: terraform
        state: present
        update_cache: yes

    - name: Verify Terraform installation
      ansible.builtin.shell: terraform version
      register: terraform_version
      changed_when: false

    - debug:
        msg: "Terraform installed successfully: {{ terraform_version.stdout_lines | first }}"

    - name: Install K3s without Traefik
      ansible.builtin.shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --write-kubeconfig-mode 644" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s service to start
      ansible.builtin.service_facts:

    - name: Verify K3s status
      ansible.builtin.shell: k3s kubectl get nodes
      register: k3s_status
      changed_when: false

    - debug:
        msg: "K3s cluster is running without Traefik:\n{{ k3s_status.stdout }}"