name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*.*.*'  # like v1.0.0

    paths:
      - app/**

jobs:
  build:
    uses: mhassaankhokhar/reusable-templates/.github/workflows/build-template.yml@master
    with:
      DOCKER_IMAGE: "mhassaankhokhar/filter-stack"
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}